# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodgrp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bussiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bussiness_type', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('retype', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('usertype', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('donor', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('dob', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=100)),
                ('blood', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('pancard', models.IntegerField()),
                ('gst', models.IntegerField()),
                ('bs_type', models.IntegerField()),
            ],
        ),
    ]
