# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-27 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0004_auto_20181227_1212'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationdata',
            table=None,
        ),
    ]
