# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_auto_20181227_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationData',
            new_name='RegistrationDatas',
        ),
    ]
