# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0006_auto_20181228_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdatas',
            name='email',
        ),
        migrations.AddField(
            model_name='registrationdatas',
            name='Usertype',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
