# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_auto_20181228_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdatas',
            name='Usertype',
        ),
        migrations.AddField(
            model_name='registrationdatas',
            name='usertype',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
