# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_auto_20181228_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdatas',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
