# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_auto_20181228_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
