# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0016_auto_20190108_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationDatas1',
            new_name='RegistrationDatas',
        ),
    ]
