# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0017_auto_20190108_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdatas',
            name='phone',
            field=models.IntegerField(default=10),
        ),
    ]
