# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0019_auto_20190108_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationdatas',
            name='retype',
        ),
        migrations.RemoveField(
            model_name='registrationdatas',
            name='username',
        ),
    ]
