# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0021_auto_20190108_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDatas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
