# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0023_districtmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='districtmodel',
            old_name='dis',
            new_name='district',
        ),
    ]
