# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0025_bloodmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='gst',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='pancard',
            field=models.CharField(max_length=10),
        ),
    ]
