# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0026_auto_20190218_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_emp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=10)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('money', models.IntegerField(verbose_name=10)),
                ('descrption', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
    ]
