# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0028_auto_20190218_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_emp',
            name='image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
