# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0029_auto_20190218_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='project_emp',
            new_name='project_employee',
        ),
    ]
