# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0030_auto_20190218_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_employee',
            name='end_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project_employee',
            name='image',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
