# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0037_auto_20190226_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='profit_loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('transaction_date', models.CharField(max_length=100)),
                ('frgn_key_PL', models.CharField(max_length=100)),
            ],
        ),
    ]
