# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0038_profit_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dontation_portal',
            name='foreign_donation_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
