# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-27 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0040_auto_20190226_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='dontation_portal',
            name='value_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
