# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0041_dontation_portal_value_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_employee',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
