# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0042_project_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='profit_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('bill_name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('project_id', models.CharField(max_length=100)),
                ('transaction_date', models.CharField(max_length=100)),
            ],
        ),
    ]
