# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0043_profit_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit_account',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='profit_account',
            old_name='transaction_type',
            new_name='type_transaction',
        ),
    ]
