# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0044_auto_20190306_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_account',
            name='expense_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
