# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0045_profit_account_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit_account',
            name='foreign_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
