# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0046_profit_account_foreign_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
