# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0047_userprofilemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='status',
        ),
    ]
